# Generated by Django 6.0.3 on 2026-04-04 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='provider',
            name='rating',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=3),
        ),
        migrations.AddField(
            model_name='provider',
            name='reviews',
            field=models.IntegerField(default=0),
        ),
    ]
